### ISSUE TITLE
Lint error - <manifest> does not match expected structure

### ISSUE THREAD

**Issue by robinwhittleton** [ryanodor/jack-london_son-of-the-wolf#3]
The manifest is missing the cover.jpg file. Run `print-manifest-and-spine` again and copy over the manifest section to fix.

**Comment by ryanodor** [comment]
content.opf seems to include a manifest item for cover.jpg in this repo. I got the same error when I ran the linter. After executing print-manifest-and-spine tool again, the cover.jpg line item is not included and still produces the error "does not match expected structure"
