### ISSUE TITLE
Song markup needs equivalent CSS

### ISSUE THREAD

**Issue by robinwhittleton** [ryanodor/jack-london_son-of-the-wolf#6]
Can you copy over the CSS from https://standardebooks.org/contribute/semantics#poetry (leaving out the `i2` class) and replace `poem` with `song`?

**Comment by ryanodor** [comment]
Complete.

**Comment by ryanodor** [comment]
copying the code produces and error in the lint tool for unused css, after changing "poem" to "song". should I remove the offending css?

**Comment by robinwhittleton** [comment]
Yeah, just remove the `[epub|type~="z3998:song"] p + p` block.
