### ISSUE TITLE
Language markup

### ISSUE THREAD

**Issue by robinwhittleton** [ryanodor/jack-london_son-of-the-wolf#7]
A few things that need fix-ups here:

- There are a few `<i>`s with missing language attributes. For example, `<i>coureurs du bois</i>` should be `<i xml:lang="fr">coureurs du bois</i>`.
- There are also a few that should probably just be removed, for example `<i>parkas</i>` doesn’t need to be italicised as it’s a common word now (specifically it’s in MW: https://www.merriam-webster.com/dictionary/parka).
- There are a couple of `<em>`s that I think originally were meant to mark up foreign language: `<em>sangfroid</em>` and `<em>hooch</em>`. Both those are in MW so can be removed.
- There are also a few occasions of french that should have italics and an xml:lang attribute added (e.g. “La petite squaw: mon Mason brav”).

The typography manual has more info: https://standardebooks.org/contribute/typography#italics-or-quotes.

**Comment by ryanodor** [comment]
I haven't been able to find "che-cha-qua" or "chechaqua" in MW, a French Dictionary, or Wikipedia. What do you suggest for marking up this word?

**Comment by robinwhittleton** [comment]
Seems to be a variant of [cheechako](https://www.merriam-webster.com/dictionary/cheechako) which is in MW. But it’s somewhat obscure, so let’s double-check with Alex as to whether we want to modernise the spelling to that and remove the italics, or whether we should use `xml:lang="chn"` (https://en.wikipedia.org/wiki/Chinook_Jargon).

**Comment by ryanodor** [comment]
added xml:lang="chn"
